In [1]:
import pandas as pd
import numpy as np

In [3]:
#Collecting Records of Division I college basketball seasons of past 10 years
cbb2014 = pd.read_csv('cbb14.csv')
cbb2014
cbb2015 = pd.read_csv('cbb15.csv')
cbb2015
cbb2016 = pd.read_csv('cbb16.csv')
cbb2016
cbb2017 = pd.read_csv('cbb17.csv')
cbb2017
cbb2018 = pd.read_csv('cbb18.csv')
cbb2018
cbb2019 = pd.read_csv('cbb19.csv')
cbb2019
cbb2020 = pd.read_csv('cbb20.csv')
cbb2020
cbb2021 = pd.read_csv('cbb21.csv')
cbb2021
cbb2022 = pd.read_csv('cbb22.csv')
cbb2022
cbb2023 = pd.read_csv('cbb23.csv')
cbb2023

,TEAM,CONF,Year,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,...,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED
0,Kansas,B12,2023,36,28,113.8,92.3,0.9177,52.6,47.0,...,29.8,31.1,53.0,47.2,34.7,31.0,69.0,10.1,R32,1.0
1,Purdue,B10,2023,35,29,117.9,93.7,0.9333,51.8,47.2,...,37.2,19.2,54.1,47.2,32.2,31.3,63.9,9.4,R64,1.0
2,Alabama,SEC,2023,37,31,116.1,89.0,0.9548,52.1,41.3,...,36.6,32.6,53.8,40.8,33.5,28.3,72.6,10.2,S16,1.0
3,Houston,Amer,2023,37,33,117.3,90.3,0.9532,52.3,42.7,...,28.9,35.7,53.1,43.4,34.0,27.9,63.4,8.0,S16,1.0
4,Texas,B12,2023,38,29,116.1,91.8,0.9371,53.3,48.1,...,30.5,33.7,54.0,47.9,34.7,32.4,68.5,7.5,E8,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,Toledo,MAC,2023,34,27,119.9,109.6,0.7369,56.3,52.9,...,34.4,27.5,54.6,52.1,39.7,36.1,69.5,-1.2,NaN,NaN
359,Liberty,ASun,2023,33,27,111.4,97.3,0.8246,55.5,49.3,...,26.2,27.8,56.4,48.6,36.4,33.6,64.4,-2.0,NaN,NaN
360,Utah Valley,WAC,2023,34,28,107.1,94.6,0.8065,51.7,44.0,...,35.6,28.7,52.5,42.8,33.4,31.1,69.8,-0.3,NaN,NaN
361,UAB,CUSA,2023,38,29,112.4,97.0,0.8453,50.3,47.3,...,35.7,28.9,48.8,47.2,35.6,31.6,70.7,-0.5,NaN,NaN
362,North Texas,CUSA,2023,36,31,110.0,93.8,0.8622,51.2,44.5,...,31.0,40.2,49.6,44.2,35.7,30.1,58.7,1.1,NaN,NaN

In [4]:
#Combining record for past 10 Years
cbb_data = pd.concat([cbb2014, cbb2015, cbb2016, cbb2017, cbb2018, cbb2019, cbb2020, cbb2021, cbb2022, cbb2023])
cbb_data

,TEAM,CONF,Year,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,...,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,RK,EFGD_D
0,Arizona,P12,2014,38,33,116.2,87.4,0.9636,51.7,42.3,...,50.7,40.2,36.4,32.0,64.3,9.4,E8,1.0,NaN,NaN
1,Florida,SEC,2014,39,36,115.9,88.4,0.9575,52.2,45.4,...,51.3,43.5,35.9,33.0,63.1,11.7,F4,1.0,NaN,NaN
2,Virginia,ACC,2014,37,30,114.6,89.5,0.9449,50.8,44.2,...,49.0,42.1,36.9,32.3,61.2,8.2,S16,1.0,NaN,NaN
3,Wichita St.,MVC,2014,35,34,116.4,93.0,0.9295,52.4,44.7,...,52.3,43.6,35.0,31.1,65.1,8.1,R32,1.0,NaN,NaN
4,Kansas,B12,2014,35,25,119.2,95.6,0.9270,54.2,47.1,...,55.5,44.3,34.0,35.5,68.2,6.9,R32,2.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,Toledo,MAC,2023,34,27,119.9,109.6,0.7369,56.3,52.9,...,54.6,52.1,39.7,36.1,69.5,-1.2,NaN,NaN,NaN,NaN
359,Liberty,ASun,2023,33,27,111.4,97.3,0.8246,55.5,49.3,...,56.4,48.6,36.4,33.6,64.4,-2.0,NaN,NaN,NaN,NaN
360,Utah Valley,WAC,2023,34,28,107.1,94.6,0.8065,51.7,44.0,...,52.5,42.8,33.4,31.1,69.8,-0.3,NaN,NaN,NaN,NaN
361,UAB,CUSA,2023,38,29,112.4,97.0,0.8453,50.3,47.3,...,48.8,47.2,35.6,31.6,70.7,-0.5,NaN,NaN,NaN,NaN
362,North Texas,CUSA,2023,36,31,110.0,93.8,0.8622,51.2,44.5,...,49.6,44.2,35.7,30.1,58.7,1.1,NaN,NaN,NaN,NaN

In [5]:
#Number of matches played per year
cbb_data['Year'].value_counts().sort_index()

2014    351
2015    351
2016    351
2017    351
2018    351
2019    353
2020    353
2021    347
2022    358
2023    363
Name: Year, dtype: int64

In [7]:
#Champions of every season and their games played and matches won
cbb_data[cbb_data['POSTSEASON'] == 'Champions'][['Year', 'TEAM', 'G', 'W']].sort_values(by = 'Year').reset_index()

   index  Year            TEAM   G   W
0     24  2014     Connecticut  40  32
1      1  2015            Duke  39  35
2    327  2016       Villanova  40  35
3      1  2017  North Carolina  39  33
4      0  2018       Villanova  40  36
5      1  2019        Virginia  38  35
6      1  2021          Baylor  24  22
7      1  2022          Kansas  40  34
8     12  2023     Connecticut  39  31

In [8]:
#Adding win Ratio Column
cbb_data['WIN RATIO'] = cbb_data['W'] * 100 /cbb_data['G']

In [9]:
cbb_data[cbb_data['POSTSEASON'] == 'Champions'][['Year', 'TEAM', 'G', 'W', 'WIN RATIO']].sort_values(by = 'Year').reset_index()

   index  Year            TEAM   G   W  WIN RATIO
0     24  2014     Connecticut  40  32  80.000000
1      1  2015            Duke  39  35  89.743590
2    327  2016       Villanova  40  35  87.500000
3      1  2017  North Carolina  39  33  84.615385
4      0  2018       Villanova  40  36  90.000000
5      1  2019        Virginia  38  35  92.105263
6      1  2021          Baylor  24  22  91.666667
7      1  2022          Kansas  40  34  85.000000
8     12  2023     Connecticut  39  31  79.487179

In [10]:
#Top 8 Teams every season 
cbb_top8 = cbb_data[cbb_data['POSTSEASON'] == 'S16' ][['Year', 'TEAM', 'G', 'W', 'WIN RATIO']].reset_index()
cbb_top8

    index  Year           TEAM   G   W  WIN RATIO
0       2  2014       Virginia  37  30  81.081081
1      10  2014       Iowa St.  36  28  77.777778
2      12  2014     Louisville  37  31  83.783784
3      14  2014  San Diego St.  34  29  85.294118
4      15  2014           UCLA  37  28  75.675676
..    ...   ...            ...  ..  ..        ...
67     11  2023         Xavier  37  27  72.972973
68     15  2023      Tennessee  36  25  69.444444
69     27  2023   Michigan St.  34  21  61.764706
70     31  2023       Arkansas  36  22  61.111111
71     61  2023      Princeton  30  23  76.666667

[72 rows x 6 columns]

In [35]:
#TEAMS ending top 8 most number of times in past 10 years
cbb_data[cbb_data['POSTSEASON'] == 'S16'][['TEAM']].value_counts().head(10)

TEAM
UCLA             5
Michigan         3
West Virginia    3
Tennessee        3
Purdue           3
Gonzaga          3
Iowa St.         3
Alabama          2
Wisconsin        2
Texas A&M        2
dtype: int64

In [82]:
#Win Ratio of top 8 teams Year wise
cbb_top8[cbb_top8['G'] > 29].groupby('Year')['WIN RATIO'].mean().reset_index()

   Year  WIN RATIO
0  2014  74.757110
1  2015  68.953621
2  2016  72.425729
3  2017  77.468917
4  2018  72.866795
5  2019  79.423813
6  2021  80.000000
7  2022  75.717634
8  2023  74.839582

In [83]:
#cbb_top8[cbb_top8['TEAM'] == 'Loyola Chicago']

In [88]:
cbb_data.to_csv('cbb_data.csv', index = False)
new = pd.read_csv('cbb_data.csv')
new.head(10)

,TEAM,CONF,Year,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,...,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,RK,EFGD_D,WIN RATIO
0,Arizona,P12,2014,38,33,116.2,87.4,0.9636,51.7,42.3,...,40.2,36.4,32.0,64.3,9.4,E8,1.0,NaN,NaN,86.842105
1,Florida,SEC,2014,39,36,115.9,88.4,0.9575,52.2,45.4,...,43.5,35.9,33.0,63.1,11.7,F4,1.0,NaN,NaN,92.307692
2,Virginia,ACC,2014,37,30,114.6,89.5,0.9449,50.8,44.2,...,42.1,36.9,32.3,61.2,8.2,S16,1.0,NaN,NaN,81.081081
3,Wichita St.,MVC,2014,35,34,116.4,93.0,0.9295,52.4,44.7,...,43.6,35.0,31.1,65.1,8.1,R32,1.0,NaN,NaN,97.142857
4,Kansas,B12,2014,35,25,119.2,95.6,0.9270,54.2,47.1,...,44.3,34.0,35.5,68.2,6.9,R32,2.0,NaN,NaN,71.428571
5,Michigan,B10,2014,37,28,125.0,99.9,0.9295,55.7,49.4,...,50.2,40.2,31.8,62.6,7.7,E8,2.0,NaN,NaN,75.675676
6,Villanova,BE,2014,34,29,115.2,92.5,0.9260,53.6,46.3,...,43.0,35.6,35.3,67.6,8.3,R32,2.0,NaN,NaN,85.294118
7,Wisconsin,B10,2014,38,30,122.7,95.9,0.9441,53.3,47.2,...,45.9,37.6,34.1,63.9,7.9,F4,2.0,NaN,NaN,78.947368
8,Creighton,BE,2014,35,27,125.2,101.9,0.9144,58.9,48.5,...,47.0,41.4,34.2,65.4,5.6,R32,3.0,NaN,NaN,77.142857
9,Duke,ACC,2014,35,26,125.9,98.6,0.9432,53.8,49.3,...,50.3,39.5,30.7,66.7,6.5,R64,3.0,NaN,NaN,74.285714

In [13]:
import altair as alt

In [18]:
win_ratio_top8 = cbb_top8[cbb_top8['G'] > 29].groupby('Year')['WIN RATIO'].mean().reset_index()
win_ratio_top8

   Year  WIN RATIO
0  2014  74.757110
1  2015  68.953621
2  2016  72.425729
3  2017  77.468917
4  2018  72.866795
5  2019  79.423813
6  2021  80.000000
7  2022  75.717634
8  2023  74.839582

In [25]:
alt.Chart(win_ratio_top8).mark_area(
    color="lightblue",
    interpolate='step-after',
    line=True
).encode(
    x='Year',
    y='WIN RATIO'
).transform_filter(alt.datum.symbol == 'GOOG')

alt.Chart(...)

In [27]:
from vega_datasets import data

source = data.cars()

alt.Chart(source).mark_circle(size=100).encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
    tooltip=['Name', 'Origin', 'Horsepower', 'Miles_per_Gallon']
).interactive()

alt.Chart(...)